### ISSUE TITLE
More documents

### ISSUE THREAD

**Issue by ymgyt** [ymgyt/tracing-cloudwatch#5]
We should improve documents

## Tasks
- [x] Improve rustdoc
- [x] Describe the case where the log group does not exist
- [x] Describe the case where the log stream does not exist
- [x] How to configure retry
- [x] How to configure timeout
